### ISSUE TITLE
Test file with a wrong name.

### ISSUE THREAD

**Issue by danielcarlman** [bradtraversy/traversy-js-challenges#1]
The file `06-hash-tables-maps-sets/13-add-get-values-method/get-values.test.js` should be renamed to `06-hash-tables-maps-sets/13-add-get-values-method/get-values-test.js`. 

So basically replace the dot with a dash. Otherwise, Jest fails the test. This might confuse people when they try to test the first problems (i.e. "Hello World) and see an error despite their solution being correct.

**Comment by bradtraversy** [comment]
Thanks so much. I was bound to miss one :) Fixed
