### ISSUE TITLE
One Jest Test is named with a dot instead of a hyphen

### ISSUE THREAD

**Issue by codysechelski** [bradtraversy/traversy-js-challenges#2]
The file `06-hash-tables-maps-sets/13-add-get-values-method/get-values.test.js` should be renamed to `06-hash-tables-maps-sets/13-add-get-values-method/get-values-test.js`. Otherwise, it fails when running earlier tests.

This might be confusing to some newer developers.

**Comment by bradtraversy** [comment]
It has been renamed in the latest commit. I also updated it in the course files. Thank you
