### ISSUE TITLE
Error in 02-basic-challenges-2/05-find-missing-letter/find-missing-letter-run.js

### ISSUE THREAD

**Issue by codysechelski** [bradtraversy/traversy-js-challenges#3]
In section `02-basic-chalanges-2` >  `05-find-missing-letter`,  the run file is missing 2 letters (`d` and `e`), rather than one

```javascript
const findMissingLetter = require('./find-missing-letter');

result = findMissingLetter(['a', 'b', 'c', 'f', 'g']);

console.log(result);
```

A simple oversight, I'm sure. Loving the challenges, BTW!

**Comment by bradtraversy** [comment]
Thanks for that. I will fix that now
